version: "3.5"

services:
  nginx-download:
    image: opensusebr/mirror-nginx-download
    volumes:
      - fancyindex:/srv/www/fancyindex
      - opensuse:/srv/pub/opensuse/
    networks:
      - traefik
    ulimits:
      nofile:
        soft: 120000
        hard: 120000
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 256M
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik
        # https config
        - traefik.http.routers.download-https.rule=Host(`download.opensuse.net.br`) || Host(`rsync.opensuse.net.br`) || Host(`opensuse.net.br`)
        - traefik.http.routers.download-https.entrypoints=https
        - traefik.http.routers.download-https.tls=true
        - traefik.http.routers.download-https.tls.certresolver=letsencrypt
        - traefik.http.routers.download-https.service=download
        # http config
        - traefik.http.routers.download-http.rule=Host(`download.opensuse.net.br`) || Host(`rsync.opensuse.net.br`) || Host(`opensuse.net.br`)
        - traefik.http.routers.download-http.entrypoints=http
        - traefik.http.routers.download-http.service=download
        # service config
        - traefik.http.services.download.loadbalancer.server.port=80

  rsync-server:
    image: opensusebr/mirror-rsync-server
    volumes:
      - opensuse:/srv/pub/opensuse/
    networks:
      - traefik
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 64M
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik
        # tcp config
        - traefik.tcp.routers.content-tcp.rule=HostSNI(`*`)
        - traefik.tcp.routers.content-tcp.entrypoints=rsync
        - traefik.tcp.routers.content-tcp.service=content
        # service config
        - traefik.tcp.services.content.loadbalancer.server.port=873

  rsync-transfer:
    image: opensusebr/mirror-rsync-transfer
    environment:
      # RSYNC_HOST: rsync.opensuse.org
      RSYNC_HOST: stage.opensuse.org
      RSYNC_MODULE: opensuse-full-with-factory
      RSYNC_PATH: /opensuse/
      RSYNC_USER: opensuse
      RSYNC_PASSWORD:
    configs:
      - source: rsync-include
        target: /etc/rsync-include.txt
    volumes:
      - opensuse:/srv/pub/opensuse/
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        # run every hour
        - "swarm.cronjob.schedule=0 */1 * * *"
        - "swarm.cronjob.skip-running=true"
        # limit replicas to one, rsync can't run in parallel
        - "swarm.cronjob.replicas=1"
      restart_policy:
        condition: none

configs:
  rsync-include:
    external: true

networks:
  traefik:
    external: true

volumes:
  fancyindex:
    external: true
  opensuse:
    external: true
